//
// Created by Lukas on 8/9/2015.
//

#ifndef NDKTEST_CPSR_UTIL_H
#define NDKTEST_CPSR_UTIL_H

#define CPSR_FLAG_THUMB (1 << 5)
#define CPSR_FLAG_DISABLE_FIQ_INTERRUPTS (1 << 6)
#define CPSR_FLAG_DISABLE_IRQ_INTERRUPTS (1 << 7)
#define CPSR_FLAG_JAZELLE (1 << 24)
#define CPSR_FLAG_UNDERFLOW_SATURATION (1 << 27)
#define CPSR_FLAG_SIGNED_OVERFLOW (1 << 28)
#define CPSR_FLAG_CARRY (1 << 29)
#define CPSR_FLAG_ZERO (1 << 30)
#define CPSR_FLAG_NEGATIVE (1 << 31)

#endif //NDKTEST_CPSR_UTIL_H
