/*
 * Copyright 2016 Lukas Dresel
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
//
// Created by Lukas on 1/18/2016.
//

#ifndef NDKTEST_ART_ENTRYPOINTS_PORTABLE_ENTRYPOINTS_H
#define NDKTEST_ART_ENTRYPOINTS_PORTABLE_ENTRYPOINTS_H

// Pointers to functions that are called by code generated by compiler's adhering to the portable
// compiler ABI.
struct PACKED(4) PortableEntryPoints
{
// Invocation
/*
void (*pPortableImtConflictTrampoline)(mirror::ArtMethod*);
void (*pPortableResolutionTrampoline)(mirror::ArtMethod*);
void (*pPortableToInterpreterBridge)(mirror::ArtMethod*);
 */
    void (*pPortableImtConflictTrampoline)(void*);
    void (*pPortableResolutionTrampoline)(void*);
    void (*pPortableToInterpreterBridge)(void*);
};

#endif //NDKTEST_ART_ENTRYPOINTS_PORTABLE_ENTRYPOINTS_H
