//
// Created by Lukas on 1/18/2016.
//

#ifndef NDKTEST_ART_ENTRYPOINTS_PORTABLE_ENTRYPOINTS_H
#define NDKTEST_ART_ENTRYPOINTS_PORTABLE_ENTRYPOINTS_H

// Pointers to functions that are called by code generated by compiler's adhering to the portable
// compiler ABI.
struct PACKED(4) PortableEntryPoints
{
// Invocation
/*
void (*pPortableImtConflictTrampoline)(mirror::ArtMethod*);
void (*pPortableResolutionTrampoline)(mirror::ArtMethod*);
void (*pPortableToInterpreterBridge)(mirror::ArtMethod*);
 */
    void (*pPortableImtConflictTrampoline)(void*);
    void (*pPortableResolutionTrampoline)(void*);
    void (*pPortableToInterpreterBridge)(void*);
};

#endif //NDKTEST_ART_ENTRYPOINTS_PORTABLE_ENTRYPOINTS_H
