/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lukas_ndktest_MainActivity */

#ifndef _Included_com_example_lukas_ndktest_MainActivity
#define _Included_com_example_lukas_ndktest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_lukas_ndktest_MainActivity_BIND_ABOVE_CLIENT
#define com_example_lukas_ndktest_MainActivity_BIND_ABOVE_CLIENT 8L
#undef com_example_lukas_ndktest_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_example_lukas_ndktest_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_example_lukas_ndktest_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_example_lukas_ndktest_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_example_lukas_ndktest_MainActivity_BIND_AUTO_CREATE
#define com_example_lukas_ndktest_MainActivity_BIND_AUTO_CREATE 1L
#undef com_example_lukas_ndktest_MainActivity_BIND_DEBUG_UNBIND
#define com_example_lukas_ndktest_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_example_lukas_ndktest_MainActivity_BIND_IMPORTANT
#define com_example_lukas_ndktest_MainActivity_BIND_IMPORTANT 64L
#undef com_example_lukas_ndktest_MainActivity_BIND_NOT_FOREGROUND
#define com_example_lukas_ndktest_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_example_lukas_ndktest_MainActivity_BIND_WAIVE_PRIORITY
#define com_example_lukas_ndktest_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef com_example_lukas_ndktest_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_example_lukas_ndktest_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_example_lukas_ndktest_MainActivity_CONTEXT_INCLUDE_CODE
#define com_example_lukas_ndktest_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_example_lukas_ndktest_MainActivity_CONTEXT_RESTRICTED
#define com_example_lukas_ndktest_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_example_lukas_ndktest_MainActivity_MODE_APPEND
#define com_example_lukas_ndktest_MainActivity_MODE_APPEND 32768L
#undef com_example_lukas_ndktest_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_example_lukas_ndktest_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_example_lukas_ndktest_MainActivity_MODE_MULTI_PROCESS
#define com_example_lukas_ndktest_MainActivity_MODE_MULTI_PROCESS 4L
#undef com_example_lukas_ndktest_MainActivity_MODE_PRIVATE
#define com_example_lukas_ndktest_MainActivity_MODE_PRIVATE 0L
#undef com_example_lukas_ndktest_MainActivity_MODE_WORLD_READABLE
#define com_example_lukas_ndktest_MainActivity_MODE_WORLD_READABLE 1L
#undef com_example_lukas_ndktest_MainActivity_MODE_WORLD_WRITEABLE
#define com_example_lukas_ndktest_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_DIALER
#define com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_DISABLE
#define com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_example_lukas_ndktest_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_example_lukas_ndktest_MainActivity_RESULT_CANCELED
#define com_example_lukas_ndktest_MainActivity_RESULT_CANCELED 0L
#undef com_example_lukas_ndktest_MainActivity_RESULT_FIRST_USER
#define com_example_lukas_ndktest_MainActivity_RESULT_FIRST_USER 1L
#undef com_example_lukas_ndktest_MainActivity_RESULT_OK
#define com_example_lukas_ndktest_MainActivity_RESULT_OK -1L
/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    testOverwriteAtoi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_testOverwriteAtoi
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    testOverwriteJNIEnvFunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_testOverwriteJNIEnvFunc
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    testOverwriteOwnFunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_testOverwriteOwnFunction
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    testBreakpointAtoi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_testBreakpointAtoi
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    testHookingAtoi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_testHookingAtoi
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    testHookingAndroidLogPrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_testHookingAndroidLogPrint
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    dumpJEnvContent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_dumpJEnvContent
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    dumpProcessMemoryMap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_dumpProcessMemoryMap
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    dumpProcAlignmentMap
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_dumpProcAlignmentMap
  (JNIEnv *, jobject);

/*
 * Class:     com_example_lukas_ndktest_MainActivity
 * Method:    setMemoryProtection
 * Signature: (JJZZZ)V
 */
JNIEXPORT void JNICALL Java_com_example_lukas_ndktest_MainActivity_setMemoryProtection
  (JNIEnv *, jobject, jlong, jlong, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
