#ifndef _CONFIG_CONSTANTS_H
#define _CONFIG_CONSTANTS_H

#define ARCHITECTURE_ARM 1
#define ARCHITECTURE_ARM64 2
#define ARCHITECTURE_x86 3
#define ARCHITECTURE_x86_64 4
#define ARCHITECTURE_MIPS 5
#define ARCHITECTURE_MIPS64 6

#define LOG_LEVEL_ALL 0
#define LOG_LEVEL_VERBOSE 1
#define LOG_LEVEL_DEBUG 2
#define LOG_LEVEL_INFO 3
#define LOG_LEVEL_WARN 4
#define LOG_LEVEL_ERROR 5
#define LOG_LEVEL_FATAL 6
#define LOG_LEVEL_NOLOG 7


// Supported Oat versions
#define OAT_VERSION_045 0
#define OAT_VERSION_064 1


#endif





