#ifndef _CONFIG_CONSTANTS_H
#define _CONFIG_CONSTANTS_H

#define ARCHITECTURE_ARM 1
#define ARCHITECTURE_x86 2

#define LOG_LEVEL_ALL 0
#define LOG_LEVEL_VERBOSE 1
#define LOG_LEVEL_DEBUG 2
#define LOG_LEVEL_INFO 3
#define LOG_LEVEL_WARN 4
#define LOG_LEVEL_ERROR 5
#define LOG_LEVEL_FATAL 6
#define LOG_LEVEL_NOLOG 7

#endif





